services:
  grin-olivetin:
    build:
      context: ../../
      dockerfile: base-olivetin/Dockerfile
      target: olivetin_grin_combined_build
    container_name: grin-main-monitor-container
    networks:
      - grin-mainnet-network
    image: grin-olivetin-mainnnet 
    environment:
      - PORT=1337
      - NODE_API_ADDR=grin-node-mainnet-master-container:3413
      - NODE_CHAIN_TYPE=main
      - OWNER_API_ADDRESS=grin-wallet-testnet-contracts-container:3415
    volumes:
      - ../config/combined.yaml:/etc/OliveTin/config.yaml
      - ../json-rpc/node:/etc/OliveTin/json-rpc/node
      - main_grin-home-mainnet-master:/grin-node-home
    ports:
      - "1337:1337"
    restart: unless-stopped

volumes:
  main_grin-home-mainnet-master:
    external: true

networks:
  grin-mainnet-network:
    name: grin_mainnet_network
    external: true