services:
  # Grin Wallet Listeners - Built from contracts
  grin-wallet-mainnet-contracts:
    build:
      context: ../../../
      dockerfile: base-build/Dockerfile.wallet
      target: grin_wallet_contracts
    container_name: grin-wallet-mainnet-contracts-container
    networks:
      - grin-mainnet-network
    image: grin-wallet-mainnet-contracts
    command: ["owner_api", "--run_foreign"]
    environment:
      - RUST_BACKTRACE=1
      - GRIN_CHAIN_TYPE="Testnet"
      - OWNER_API_LISTEN_INTERFACE="0.0.0.0"
      - WALLET_API_LISTEN_PORT=13415
      - OWNER_API_LISTEN_PORT=13415
      - NODE_API_SECRET_PATH="/grin-node-home/.grin/test/.foreign_api_secret"
      - NODE_API_HTTP_ADDR="http://grin-node-testnet-master-container:13413"
    expose:
      - "3415"
    ports:
      - "3415:3415"
    volumes:
      - grin-wallet-home-mainnet-contracts:/home/grinuser
      - main_grin-home-mainnet-master:/grin-node-home

volumes:
  grin-wallet-home-mainnet-contracts:
  main_grin-home-mainnet-master:
    external: true

networks:
  grin-mainnet-network:
    name: grin_mainnet_network
    external: true