services:
  # Grin Wallet Listeners - Built from master
  grin-wallet-mainnet-master:
    build:
      context: ../../../
      dockerfile: base-build/Dockerfile.wallet
      target: grin_wallet_master
    container_name: grin_wallet_mainnet_master_container
    networks:
      - grin-mainnet-network
    image: grin-wallet-mainnet-master
    command: ["owner_api", "--run_foreign"]
    environment:
      - RUST_BACKTRACE=1
    expose:
      - "3415"
    ports:
      - "3415:3415"
    volumes:
      - ../../configs/mainnet/grin-wallet.toml:/home/grinuser/.grin/main/grin-wallet.toml
      - grin-wallet-home-mainnet-master:/home/grinuser
      - main_grin-home-mainnet-master:/grin-node-home

volumes:
  grin-wallet-home-mainnet-master:
  main_grin-home-mainnet-master:
    external: true

networks:
  grin-mainnet-network:
    name: grin_mainnet_network
    external: true