services:
  # Grin Mainnet Node - Built from master
  grin-node-mainnet-master:
    build:
      context: ../../
      dockerfile: base-build/Dockerfile.node.master
      target: grin_node_master
    container_name: grin_node_mainnet_master_container
    networks:
      - grin-mainnet-network
    image: grin-node-mainnet-master
    environment:
      - RUST_BACKTRACE=1
    expose:
      - "3413"
      - "3414"
    ports:
      - "3413:3413"
      - "3414:3414"
    volumes:
      - ../configs/mainnet/grin-server.toml:/home/grinuser/.grin/main/grin-server.toml
      - grin-home-mainnet-master:/home/grinuser

volumes:
  grin-home-mainnet-master:

networks:
  grin-mainnet-network:
    name: grin_mainnet_network