actions:
  - title: Node Sync Status
    popupOnStart: execution-dialog-stdout-only
    shell: /etc/OliveTin/json-rpc/node/execute_get_status.sh
    icon: ping
    timeout: 5

  - title: Get Block
    popupOnStart: execution-dialog-stdout-only
    shell: /etc/OliveTin/json-rpc/node/execute_get_block.sh
    icon: ping
    timeout: 5
    arguments:
      - name: block_number
        type: ascii_sentence
        description: Block Number
        
  - title: Get Outputs
    popupOnStart: execution-dialog-stdout-only
    shell: /etc/OliveTin/json-rpc/node/execute_get_outputs.sh
    icon: ping
    timeout: 5
    arguments:
      - name: commits
        type:  very_dangerous_raw_string
        description: Commits

  - title: Create Wallet
    popupOnStart: execution-dialog-stdout-only
    shell: node /etc/OliveTin/owner_api_client/src/create_wallet.js
    arguments:
      - name: wallet_password
        type: ascii_sentence
        description: Wallet Password
  - title: Wallet Summary Info
    popupOnStart: execution-dialog-stdout-only
    shell: node /etc/OliveTin/owner_api_client/src/wallet_info.js
    arguments:
      - name: wallet_password
        type: ascii_sentence
        description: Wallet Password
  - title: Wallet Txs
    popupOnStart: execution-dialog-stdout-only
    shell: node /etc/OliveTin/owner_api_client/src/wallet_txs.js
    arguments:
      - name: wallet_password
        type: ascii_sentence
        description: Wallet Password

dashboards:
  - title: All Processes
    type: fieldset
    contents:
      - title: Grin Node
        type: fieldset
        contents:
        - title: Node Sync Status
        - title: Get Block
        - title: Get Outputs
      - title: Grin Wallet
        type: fieldset
        contents:
        - title: Create Wallet      
        - title: Wallet Summary Info
        - title: Wallet Txs
